### PR TITLE
Capital GET breaks babel compile

### PR DESCRIPTION
**Pull request by gstcyr**
the capital GET is breaking babel for some reason. Changing to lower case fixes the issue.

### CODE REVIEW

**Comment by mikehardy** [comment]
Hi there @gstcyr ! No real objection to this (and feel free to use patch-package locally while we're discussing this even so you're not blocked) - but...why doesn't this happen to me? I just want to try to understand it

Here's what I've got from a `grep babel *|sort|uniq|grep -v yarn.lock` (hopefully that's enough info

Also it doesn't show up in the example that I'm aware of, is there something missing in the example?

```
babel.config.js:    ['@babel/preset-env', { targets: { node: true } }],
babel.config.js:    'module:metro-react-native-babel-preset',
gulpfile.js:    USEBABEL: argv.usebabel,
package.json:    "@babel/core": "^7.9.6",
package.json:    "babel-jest": "^25.5.1",
package.json:    "babel-loader": "^8.1.0",
package.json:    "@babel/preset-env": "^7.9.6",
package.json:    "@babel/runtime": "^7.9.6",
package.json:    "metro-react-native-babel-preset": "^0.59.0",
webpack.config.ts:        loader: 'babel-loader',
```

**Comment by gstcyr** [comment]
Hey, I have no idea. I'm using the library in an expo project using the bare workflow, and it's causing me issues when I do a react-native-web build. It works fine when just using it for android builds.

**Comment by mikehardy** [comment]
No look at all? No version check? Okay, I guess. A lack of understanding for a fix means you'll probably have a problem somewhere else but this one is inconsequential for me, so I'll merge it

**Comment by mikehardy** [comment]
4.3.2 is out

**Pull request merged**
